from typing import Protocol
from app.domain.raw_audio import RawAudio

class AudioStorage(Protocol):
    async def save(self, key: str, data: bytes) -> str: ...
    async def load(self, key: str) -> RawAudio: ...
    async def get_url(self, key: str) -> str: ...
    async def delete(self, key: str) -> None: ...
    async def exists(self, key: str) -> bool: ...