from typing import Protocol, Optional, Sequence
from uuid import UUID

from app.domain.entities import Meeting, Speaker, Person
from app.domain.speech_segment import SpeechSegment

class MeetingRepository(Protocol):
    def create(self, meeting: Meeting) -> Meeting: ...
    def get(self, meeting_id: UUID) -> Optional[Meeting]: ...
    def update_status(self, meeting_id: UUID, status: str) -> None: ...
    def list_by_status(self, status: str) -> Sequence[Meeting]: ...
    def commit(self) -> None: ...

class SpeakerRepository(Protocol):
    def bulk_create(self, speakers: list[Speaker]) -> None: ...
    def get(self, speaker_id: UUID) -> Optional[Speaker]: ...
    def list_by_meeting(self, meeting_id: UUID) -> Sequence[Speaker]: ...
    def list_unknown_by_meeting(self, meeting_id: UUID) -> Sequence[Speaker]: ...
    def list_by_ids(self, speaker_ids: list[UUID]) -> Sequence[Speaker]: ...
    def assign_person(self, speaker_id: UUID, person_id: UUID) -> None: ...
    def assign_person_bulk(self, speaker_ids: list[UUID], person_id: UUID) -> None: ...
    def get_by_meeting_and_label(self, meeting_id: UUID, diarization_label: str) -> Optional[Speaker]: ...
    def commit(self) -> None: ...

class SegmentRepository(Protocol):
    def bulk_create(self, segments: list[SpeechSegment]) -> None: ...
    def list_by_meeting(self, meeting_id: UUID) -> Sequence[SpeechSegment]: ...
    def list_by_speaker(self, speaker_id: UUID) -> Sequence[SpeechSegment]: ...
    def commit(self) -> None: ...

class PersonRepository(Protocol):
    def create(self, person: Person) -> Person: ...
    def get(self, person_id: UUID) -> Optional[Person]: ...
    def list_all(self) -> Sequence[Person]: ...